### ISSUE TITLE
Incomplete README.md

### ISSUE THREAD

**Issue by keys-i** [diyagoyal18/Online-Code-Editor#1]
Here's the issue description formatted as a markdown checklist:

---

## Incomplete README.md

**Description:**
The current `README.md` for our project is incomplete and lacks several important sections that would help new contributors and users understand and navigate the project. The following sections are either missing or need to be expanded:

**Current README.md:**

```md
Demo https://online-code-editor-theta-five.vercel.app/

# React + Vite

This template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.

Currently, two official plugins are available:

- [@vitejs/plugin-react](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md) uses [Babel](https://babeljs.io/) for Fast Refresh
- [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh
```

**Checklist:**

- [x] **Project Title and Description:**
  - [x] Provide a brief introduction to the project, what it does, and its purpose.

- [x] **Table of Contents:**
  - [x] Include a table of contents for easier navigation.

- [x] **Installation Instructions:**
  - [x] Detailed steps on how to clone the repository, install dependencies, and run the project locally.

- [x] **Usage:**
  - [x] Instructions on how to use the project after setting it up.
  - [x] Include examples and screenshots if necessary.

- [x] **Features:**
  - [x] Highlight key features of the project.

- [x] **Contributing:**
  - [x] Guidelines for contributing to the project.
  - [x] Include how to fork the repository, create branches, and submit pull requests.

- [x] **License:**
  - [x] Include the project’s license information.

- [x] **Acknowledgements:**
  - [x] Credit any resources, tools, or individuals that have contributed to the project.

- [x] **Contact Information:**
  - [x] Provide contact details or links to report issues or ask questions.

By addressing these points, we can ensure that our `README.md` is comprehensive and helpful to all users and contributors.

---

**Comment by diyagoyal18** [comment]
Thankyou for addressing the issue. I have made the necessary changes.
